name: Copy fuel.js
run-name: ${{ github.actor }} edited fuel.js, copying it to server
on:
  push:
    branches:
      - main
    paths:
      - fuel.js
    tags-ignore:
      - "*"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: './fuel.js'
          destination-username: 'KittenApps-Films'
          destination-repository: 'KittenApps-Films.github.io'
          destination-directory: 'geofs/geofs-addons/addon-scripts'
          commit-email: 'kittenappsandfilms@gmail.com'
